[versions]
agp = "8.13.2"
blurview = "version-2.0.6"
composeBom = "2026.02.00"
core = "4.6.2"
dexkit = "2.0.7"
grpcProtobuf = "1.79.0"
gson = "2.13.2"
hutoolCore = "5.8.43"
appcompat = "1.7.1"
kotlinxIoJvm = "0.1.16"
ktor = "2.3.3"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"
activity = "1.12.4"
constraintlayout = "2.2.1"
kotlin = "2.3.10"
coreKtx = "1.17.0"
mmkv = "2.3.0"
nanoHttpd = "2.3.1"
rhino = "1.3.0"
serialization = "1.10.0"
lombok = "1.18.42"
protobuf = "4.33.5"
sealedEnum = "0.7.0"
ksp = "2.3.4"
recyclerview = "1.4.0"
fastJson2 = "2.0.61"
materialPreference = "2.0.0"
preference = "1.2.1"
appcompatVersion = "1.6.1"
materialDialog = "3.3.0"
okhttpVersion = "5.3.2"
byteBuddy = "1.15.10"

[libraries]
android-tools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
blurView = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpcProtobuf" }
hutool-core = { module = "cn.hutool:hutool-core", version.ref = "hutoolCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
markdown-core = { module = "io.noties.markwon:core", version.ref = "core" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenApiBypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "6.1" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-io-jvm = { module = "org.jetbrains.kotlinx:kotlinx-io-jvm", version.ref = "kotlinxIoJvm" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanoHttpd" }
rhino-android = { module = "io.apisense:rhino-android", version.ref = "rhino" }
xposed = { module = "de.robv.android.xposed:api", version = "82" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.9.0.202403050737-r" }
sealedEnum-runtime = { module = "com.github.livefront.sealed-enum:runtime", version.ref = "sealedEnum" }
sealedEnum-ksp = { module = "com.github.livefront.sealed-enum:ksp", version.ref = "sealedEnum" }
glide = { module = "com.github.bumptech.glide:glide", version = "5.0.5" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
dexlib2 = { module = "org.smali:dexlib2", version = "2.5.2" }
google-guava = { module = "com.google.guava:guava", version = "33.5.0-android" }
google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
google-protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byteBuddy" }
byte-buddy-android = { module = "net.bytebuddy:byte-buddy-android", version.ref = "byteBuddy" }
dalvik-dx = { module = "com.jakewharton.android.repackaged:dalvik-dx", version = "16.0.1" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
material-preference = { module = "dev.rikka.rikkax.material:material-preference", version.ref = "materialPreference" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
dev-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version.ref = "appcompatVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastJson2" }
material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialog" }
material-dialogs-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialog" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version = "2.2.0" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.9.6" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

