[versions]
# noinspection UnusedVersionCatalogEntry
kotlinxSerializationJson = "1.10.0"
namespace = "moe.ouom.wekit"
# noinspection UnusedVersionCatalogEntry
minSdk = "29"
# noinspection UnusedVersionCatalogEntry
targetSdk = "36"
# noinspection UnusedVersionCatalogEntry
jdk = "21"

agp = "8.13.2"
composeBom = "2026.02.00"
core = "4.6.2"
dexkit = "2.0.7"
grpcProtobuf = "1.79.0"
accompanist = "0.37.3"
gson = "2.13.2"
hutoolCore = "5.8.43"
appcompat = "1.7.1"
kotlinxIoJvm = "0.1.16"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"
activity = "1.12.4"
constraintlayout = "2.2.1"
kotlin = "2.3.10"
coreKtx = "1.17.0"
mmkv = "2.3.0"
rhino = "1.3.0"
serialization = "1.10.0"
lombok = "1.18.42"
protobuf = "4.33.5"
ksp = "2.3.4"
recyclerview = "1.4.0"
fastJson2 = "2.0.61"
materialPreference = "2.0.0"
preference = "1.2.1"
appcompatVersion = "1.6.1"
materialDialog = "3.3.0"
okhttp = "5.3.2"
kavaref = "1.0.2"
hiddenApiBypass = "6.1"
runtime = "1.10.3"
composeMaterial3 = "1.5.0-alpha14"
libsu = "5.2.2"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
android-tools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
rikka-rikkax-material-preference = { module = "dev.rikka.rikkax.material:material-preference", version.ref = "materialPreference" }
rikka-rikkax-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version.ref = "appcompatVersion" }
material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialog" }
material-dialogs-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialDialog" }

grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpcProtobuf" }
hutool-core = { module = "cn.hutool:hutool-core", version.ref = "hutoolCore" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-io-jvm = { module = "org.jetbrains.kotlinx:kotlinx-io-jvm", version.ref = "kotlinxIoJvm" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
# noinspection UnusedVersionCatalogEntry
google-protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
google-protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
google-guava = { module = "com.google.guava:guava", version = "33.5.0-android" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastJson2" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

xposed-api = { module = "de.robv.android.xposed:api", version = "82" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
dexlib2 = { module = "org.smali:dexlib2", version = "2.5.2" }
dalvik-dx = { module = "com.jakewharton.android.repackaged:dalvik-dx", version = "16.0.1" }
hiddenApiBypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenApiBypass" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaref" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavaref" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }

rhino-android = { module = "io.apisense:rhino-android", version.ref = "rhino" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version = "2.2.0" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.9.6" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
